In [5]:
import pandas as pd

df1=pd.DataFrame({'X1':[1,2,3],
                  'X2':['X','Y','Z']},
                 index=[0,1,2])

df2=pd.DataFrame({'X3':['A','B','C'],
                  'X4':['4','5','6']},
                 index=[1,2,3])

df_outer = pd.concat([df1,df2],join='outer',axis=1)
df_inner = pd.concat([df1,df2],join='inner',axis=1)

In [21]:
import pandas as pd

df1=pd.DataFrame({'X1':[1,2,3],
                  'X2':['X','Y','Z']},
                    index=[0,1,2])

df2=pd.DataFrame({'X3':['A','B','C'],
                  'X4':[4,5,6]},
                  index=[1,2,3])

df_left = df1.join(df2,how='left')
df_right = df1.join(df2,how='right')
df_outer = df1.join(df2,how='outer')
df_inner = df1.join(df2,how='inner')

In [25]:
import pandas as pd
df1 = pd.DataFrame({'A':['X','Y','Z']})
df2 = pd.DataFrame({'B':[1,2]})

df_cross = df1.join(df2,how='cross')

In [27]:
import pandas as pd

In [31]:
df_left = pd.DataFrame({'X':['a','b','c'],
                        'M':[1,2,3]})
df_left

   X  M
0  a  1
1  b  2
2  c  3

In [33]:
df_right = pd.DataFrame({'X':['b','c','d'],
                         'N':[5,6,7]})
df_right

   X  N
0  b  5
1  c  6
2  d  7

In [35]:
pd.merge(df_left,df_right,on='X',how = 'left')

   X  M    N
0  a  1  NaN
1  b  2  5.0
2  c  3  6.0

In [37]:
pd.merge(df_left,df_right,on='X',how='left')

   X  M    N
0  a  1  NaN
1  b  2  5.0
2  c  3  6.0

In [39]:
df_right = pd.DataFrame({'X':['b','c','d'],
                         'M':[5,6,7]})
df_right

   X  M
0  b  5
1  c  6
2  d  7

In [41]:
pd.merge(df_left,df_right,on='X',how='left')

   X  M_x  M_y
0  a    1  NaN
1  b    2  5.0
2  c    3  6.0

In [43]:
df_left = pd.DataFrame({'X':['a','b','c'],
                        'M':[1,2,3]})
df_left

   X  M
0  a  1
1  b  2
2  c  3

In [51]:
df_right = pd.DataFrame({'Y':['b','c','d'],
                         'N':[5,6,7]})
df_right

   Y  N
0  b  5
1  c  6
2  d  7

In [53]:
pd.merge(df_left,df_right,left_on = 'X',right_on='Y',how = 'left')

   X  M    Y    N
0  a  1  NaN  NaN
1  b  2    b  5.0
2  c  3    c  6.0

In [55]:
pd.merge(df_left,df_right,left_on = 'X',right_on = 'Y',how = 'right')

     X    M  Y  N
0    b  2.0  b  5
1    c  3.0  c  6
2  NaN  NaN  d  7

In [57]:
pd.merge(df_left,df_right,left_on='X',right_on='Y',how = 'inner')

   X  M  Y  N
0  b  2  b  5
1  c  3  c  6

In [59]:
pd.merge(df_left,df_right,left_on='X',right_on='Y',how = 'outer')

     X    M    Y    N
0    a  1.0  NaN  NaN
1    b  2.0    b  5.0
2    c  3.0    c  6.0
3  NaN  NaN    d  7.0

In [63]:
import pandas as pd
left_data = {
    'M':[1,2,3],
    'X':['a','b','c']}
left_df = pd.DataFrame(left_data)
left_df

   M  X
0  1  a
1  2  b
2  3  c

In [71]:
right_data = {
    'X':['b','c','d'],
    'N':[22,33,44]}
right_df=pd.DataFrame(right_data)
right_df

   X   N
0  b  22
1  c  33
2  d  44

In [85]:
left_exl = left_df.merge(right_df,on = 'X',how = 'left',
                         indicator = True)
left_exl

   M  X     N     _merge
0  1  a   NaN  left_only
1  2  b  22.0       both
2  3  c  33.0       both

In [89]:
left_exl = left_exl[left_exl['_merge'] == 'left_only'].drop(columns=['_merge'])
left_exl

   M  X   N
0  1  a NaN

In [93]:
right_exl = left_df.merge(right_df,on='X',how='right',indicator=True)
right_exl

     M  X   N      _merge
0  2.0  b  22        both
1  3.0  c  33        both
2  NaN  d  44  right_only

In [97]:
right_exl = right_exl[right_exl['_merge'] == 'right_only'].drop(columns=['_merge'])
right_exl

    M  X   N
2 NaN  d  44

In [111]:
outer_exl = left_df.merge(right_df,on='X',how='outer',indicator=True)
outer_exl

     M  X     N      _merge
0  1.0  a   NaN   left_only
1  2.0  b  22.0        both
2  3.0  c  33.0        both
3  NaN  d  44.0  right_only

In [113]:
outer_exl = outer_exl[outer_exl['_merge'] != 'both'].drop(columns = ['_merge'])
outer_exl

     M  X     N
0  1.0  a   NaN
3  NaN  d  44.0

In [115]:
import pandas as pd
data = {
    'Student ID':['1','1','2','2','3','3','4','4'],
    'Subject':['Math','Art','Science','Art',
               'Math','Science','Art','Math'],
    'Midterm':[4,5,3,5,4,5,3,5],
    'Final':[3,4,5,3,4,4,4,5]}

df = pd.DataFrame(data)
df

  Student ID  Subject  Midterm  Final
0          1     Math        4      3
1          1      Art        5      4
2          2  Science        3      5
3          2      Art        5      3
4          3     Math        4      4
5          3  Science        5      4
6          4      Art        3      4
7          4     Math        5      5

In [123]:
df.pivot(index='Student ID',
         columns='Subject',
         values=['Midterm','Final'])

           Midterm              Final
Subject        Art Math Science   Art Math Science
Student ID
1              5.0  4.0     NaN   4.0  3.0     NaN
2              5.0  NaN     3.0   3.0  NaN     5.0
3              NaN  4.0     5.0   NaN  4.0     4.0
4              3.0  5.0     NaN   4.0  5.0     NaN

In [125]:
import pandas as pd
data = {
    'Student ID':['1','1','2','2','3','3','4','4'],
    'Subject':['Math','Art','Science','Art',
               'Math','Science','Art','Math'],
    'Midterm':[4,5,3,5,4,5,3,5],
    'Final':[3,4,5,3,4,4,4,5]}

In [127]:
df=pd.DataFrame(data)
df

  Student ID  Subject  Midterm  Final
0          1     Math        4      3
1          1      Art        5      4
2          2  Science        3      5
3          2      Art        5      3
4          3     Math        4      4
5          3  Science        5      4
6          4      Art        3      4
7          4     Math        5      5

In [133]:
df.pivot_table(index=['Subject','Student ID'],
               values=['Midterm','Final'])

                    Final  Midterm
Subject Student ID
Art     1             4.0      5.0
        2             3.0      5.0
        4             4.0      3.0
Math    1             3.0      4.0
        3             4.0      4.0
        4             5.0      5.0
Science 2             5.0      3.0
        3             4.0      5.0

In [135]:
import pandas as pd
import numpy as np

student_ids = [1,2,3,4]
subjects = ['Art','Math','Science']
np.random.seed(0)
scores =  np.random.randint(3,6,size=(len(student_ids),len(subjects)))

df = pd.DataFrame(scores,index=student_ids,columns=subjects)
df

   Art  Math  Science
1    3     4        3
2    4     4        5
3    3     5        3
4    3     3        5

In [137]:
df.columns.names = ['Subjects']
df.index.names = ['Students ID']

df

Subjects     Art  Math  Science
Students ID
1              3     4        3
2              4     4        5
3              3     5        3
4              3     3        5

In [141]:
df.stack().reset_index().rename(columns={0:'Final'})
#stack,将宽>>>长
#reset_index将索引转换为列
#rename重新命名数值列 0代表旧列名,值'final'为新列列名,因为前面的变换,仅剩0了

    Students ID Subjects  Final
0             1      Art      3
1             1     Math      4
2             1  Science      3
3             2      Art      4
4             2     Math      4
5             2  Science      5
6             3      Art      3
7             3     Math      5
8             3  Science      3
9             4      Art      3
10            4     Math      3
11            4  Science      5

In [147]:
import pandas as pd
data = {
    'Student ID':['1','2','3','4'],
    'Art':[4,3,5,4],
    'Math':[3,4,5,3],
    'Science':[5,4,3,4]}

df = pd.DataFrame(data)
df.columns.names = ['Subject']
melted_df = df.melt(id_vars = 'Student ID',  #其他标识的基准列,是身份
                    var_name = 'Subject',  #原列名转换为行变量的新列名
                    value_vars = ['Art','Math','Science'], #配置添加到新列名下的行变量
                    value_name = 'Score') #行变量对应的值填写到这个列名下
melted_df

   Student ID  Subject  Score
0           1      Art      4
1           2      Art      3
2           3      Art      5
3           4      Art      4
4           1     Math      3
5           2     Math      4
6           3     Math      5
7           4     Math      3
8           1  Science      5
9           2  Science      4
10          3  Science      3
11          4  Science      4

In [157]:
import pandas as pd

data = {
    ('A','Art'):[4,3,5,4],
    ('A','Math'):[3,4,5,3],
    ('A','Science'):[5,4,3,4],
    ('B','Art'):[3,4,5,4],
    ('B','Math'):[4,5,3,3],
    ('B','Science'):[5,3,4,5]}

df=pd.DataFrame(data,index=[1,2,3,4])
df

    A                B
  Art Math Science Art Math Science
1   4    3       5   3    4       5
2   3    4       4   4    5       3
3   5    5       3   5    3       4
4   4    3       4   4    3       5

In [167]:
df.columns.names = ['Class','Subject']  #配置多级索引,第一级为Class第二级为Subject
df.index.names=['Student ID'] #配置行索引名称
stacked_df = df.stack(level='Class')#将class转换为行索引,按照当前行索引为主,下沉的行索引为次级行索引
stacked_df

/var/folders/f0/8_68v87s7qg9dj06g39mn0gh0000gn/T/ipykernel_35122/1673883534.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked_df = df.stack(level='Class')#将class转换为行索引,按照当前行索引为主,下沉的行索引为次级行索引

Subject           Art  Math  Science
Student ID Class
1          A        4     3        5
           B        3     4        5
2          A        3     4        4
           B        4     5        3
3          A        5     5        3
           B        5     3        4
4          A        4     3        4
           B        4     3        5

In [195]:
import pandas as pd
import numpy as np

classes = ['A','B']
student_ids = [1,2,3,4]
subjects = ['Art','Math', 'Science']

length = len(classes) * len(student_ids) * len(subjects)
scores = np.random.randint(3,6,size=(length))

index = pd.MultiIndex.from_product(
    [classes,student_ids,subjects],
    names=['Class','Student ID','Subject'])

df = pd.DataFrame(scores, index=index,columns=['Final'])
df

                          Final
Class Student ID Subject
A     1          Art          3
                 Math         5
                 Science      3
      2          Art          5
                 Math         5
                 Science      3
      3          Art          5
                 Math         3
                 Science      3
      4          Art          3
                 Math         4
                 Science      4
B     1          Art          5
                 Math         3
                 Science      3
      2          Art          4
                 Math         3
                 Science      4
      3          Art          5
                 Math         5
                 Science      3
      4          Art          4
                 Math         4
                 Science      4

In [171]:
df.unstack('Class')

                   Final
Class                  A  B
Student ID Subject
1          Art         4  4
           Math        5  5
           Science     5  3
2          Art         3  5
           Math        4  3
           Science     4  4
3          Art         4  4
           Math        4  5
           Science     3  3
4          Art         4  4
           Math        3  4
           Science     3  4

In [175]:
df.unstack(0)

                   Final
Class                  A  B
Student ID Subject
1          Art         4  4
           Math        5  5
           Science     5  3
2          Art         3  5
           Math        4  3
           Science     4  4
3          Art         4  4
           Math        4  5
           Science     3  3
4          Art         4  4
           Math        3  4
           Science     3  4

In [177]:
df.unstack(1)

              Final
Student ID        1  2  3  4
Class Subject
A     Art         4  3  4  4
      Math        5  4  4  3
      Science     5  4  3  3
B     Art         4  5  4  4
      Math        5  3  5  4
      Science     3  4  3  4

In [179]:
df.unstack('Student ID')

              Final
Student ID        1  2  3  4
Class Subject
A     Art         4  3  4  4
      Math        5  4  4  3
      Science     5  4  3  3
B     Art         4  5  4  4
      Math        5  3  5  4
      Science     3  4  3  4

In [181]:
df.unstack(2)

                 Final
Subject            Art Math Science
Class Student ID
A     1              4    5       5
      2              3    4       4
      3              4    4       3
      4              4    3       3
B     1              4    5       3
      2              5    3       4
      3              4    5       3
      4              4    4       4

In [183]:
df.unstack('Subject')

                 Final
Subject            Art Math Science
Class Student ID
A     1              4    5       5
      2              3    4       4
      3              4    4       3
      4              4    3       3
B     1              4    5       3
      2              5    3       4
      3              4    5       3
      4              4    4       4

In [185]:
df.unstack([1,2])

           Final                                                          \
Student ID     1                2                3                4
Subject      Art Math Science Art Math Science Art Math Science Art Math
Class
A              4    5       5   3    4       4   4    4       3   4    3
B              4    5       3   5    3       4   4    5       3   4    4


Student ID
Subject    Science
Class
A                3
B                4

In [187]:
df.unstack(['Student ID','Subject'])

           Final                                                          \
Student ID     1                2                3                4
Subject      Art Math Science Art Math Science Art Math Science Art Math
Class
A              4    5       5   3    4       4   4    4       3   4    3
B              4    5       3   5    3       4   4    5       3   4    4


Student ID
Subject    Science
Class
A                3
B                4

In [203]:
df.unstack(2,1)

                 Final
Subject            Art Math Science
Class Student ID
A     1              3    5       3
      2              5    5       3
      3              5    3       3
      4              3    4       4
B     1              5    3       3
      2              4    3       4
      3              5    5       3
      4              4    4       4

In [199]:
df.unstack(['Subject','Student ID'])

           Final                                                          \
Subject      Art Math Science Art Math Science Art Math Science Art Math
Student ID     1    1       1   2    2       2   3    3       3   4    4
Class
A              3    5       3   5    5       3   5    3       3   3    4
B              5    3       3   4    3       4   5    5       3   4    4


Subject    Science
Student ID       4
Class
A                4
B                4

In [205]:
df.unstack([0,2])

           Final
Class          A                B
Subject      Art Math Science Art Math Science
Student ID
1              3    5       3   5    3       3
2              5    5       3   4    3       4
3              5    3       3   5    5       3
4              3    4       4   4    4       4

In [207]:
df.unstack([2,0])

           Final
Subject      Art Math Science Art Math Science
Class          A    A       A   B    B       B
Student ID
1              3    5       3   5    3       3
2              5    5       3   4    3       4
3              5    3       3   5    5       3
4              3    4       4   4    4       4

In [209]:
df.unstack([0,1])

           Final
Class          A           B
Student ID     1  2  3  4  1  2  3  4
Subject
Art            3  5  5  3  5  4  5  4
Math           5  5  3  4  3  3  5  4
Science        3  3  3  4  3  4  3  4

In [211]:
df.unstack([1,0])

           Final
Student ID     1  2  3  4  1  2  3  4
Class          A  A  A  A  B  B  B  B
Subject
Art            3  5  5  3  5  4  5  4
Math           5  5  3  4  3  3  5  4
Science        3  3  3  4  3  4  3  4

In [213]:
import seaborn as sns
import pandas as pd

iris_df = sns.load_dataset("iris")

In [217]:
groupby_mean = iris_df.groupby(['species']).mean()
groupby_mean

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [221]:
groupby_std = iris_df.groupby(['species']).std()
groupby_std

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          0.352490     0.379064      0.173664     0.105386
versicolor      0.516171     0.313798      0.469911     0.197753
virginica       0.635880     0.322497      0.551895     0.274650

In [223]:
groupby_var = iris_df.groupby(['species']).var()
groupby_var

            sepal_length  sepal_width  petal_length  petal_width
species
setosa          0.124249     0.143690      0.030159     0.011106
versicolor      0.266433     0.098469      0.220816     0.039106
virginica       0.404343     0.104004      0.304588     0.075433

In [227]:
groupby_cov = iris_df.groupby(['species']).cov()
groupby_cov

                         sepal_length  sepal_width  petal_length  petal_width
species
setosa     sepal_length      0.124249     0.099216      0.016355     0.010331
           sepal_width       0.099216     0.143690      0.011698     0.009298
           petal_length      0.016355     0.011698      0.030159     0.006069
           petal_width       0.010331     0.009298      0.006069     0.011106
versicolor sepal_length      0.266433     0.085184      0.182898     0.055780
           sepal_width       0.085184     0.098469      0.082653     0.041204
           petal_length      0.182898     0.082653      0.220816     0.073102
           petal_width       0.055780     0.041204      0.073102     0.039106
virginica  sepal_length      0.404343     0.093763      0.303290     0.049094
           sepal_width       0.093763     0.104004      0.071380     0.047629
           petal_length      0.303290     0.071380      0.304588     0.048824
           petal_width       0.049094     0.047629      0.048824     0.075433

In [229]:
groupby_corr = iris_df.groupby(['species']).corr()
groupby_corr

                         sepal_length  sepal_width  petal_length  petal_width
species
setosa     sepal_length      1.000000     0.742547      0.267176     0.278098
           sepal_width       0.742547     1.000000      0.177700     0.232752
           petal_length      0.267176     0.177700      1.000000     0.331630
           petal_width       0.278098     0.232752      0.331630     1.000000
versicolor sepal_length      1.000000     0.525911      0.754049     0.546461
           sepal_width       0.525911     1.000000      0.560522     0.663999
           petal_length      0.754049     0.560522      1.000000     0.786668
           petal_width       0.546461     0.663999      0.786668     1.000000
virginica  sepal_length      1.000000     0.457228      0.864225     0.281108
           sepal_width       0.457228     1.000000      0.401045     0.537728
           petal_length      0.864225     0.401045      1.000000     0.322108
           petal_width       0.281108     0.537728      0.322108     1.000000

In [231]:
import pandas as pd
import numpy as np

In [233]:
classes = ['A','B']
stu_ids = [1,2,3,4]
subjects = ['Art','Math','Science']

In [237]:
np.random.seed(0)
length = len(classes)*len(stu_ids)*len(subjects)
length

24

In [248]:
data=np.random.randint(3,6,size=length)
data

array([5, 3, 4, 5, 5, 4, 3, 4, 4, 3, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 3, 4,
       5, 5])

In [252]:
index = pd.MultiIndex.from_product(
    [classes,stu_ids,subjects],
    names=['Class','Student ID','Subject'])
index

MultiIndex([('A', 1,     'Art'),
            ('A', 1,    'Math'),
            ('A', 1, 'Science'),
            ('A', 2,     'Art'),
            ('A', 2,    'Math'),
            ('A', 2, 'Science'),
            ('A', 3,     'Art'),
            ('A', 3,    'Math'),
            ('A', 3, 'Science'),
            ('A', 4,     'Art'),
            ('A', 4,    'Math'),
            ('A', 4, 'Science'),
            ('B', 1,     'Art'),
            ('B', 1,    'Math'),
            ('B', 1, 'Science'),
            ('B', 2,     'Art'),
            ('B', 2,    'Math'),
            ('B', 2, 'Science'),
            ('B', 3,     'Art'),
            ('B', 3,    'Math'),
            ('B', 3, 'Science'),
            ('B', 4,     'Art'),
            ('B', 4,    'Math'),
            ('B', 4, 'Science')],
           names=['Class', 'Student ID', 'Subject'])

In [260]:
df = pd.DataFrame(data,index=index,columns=['Score'])
df

                          Score
Class Student ID Subject
A     1          Art          5
                 Math         3
                 Science      4
      2          Art          5
                 Math         5
                 Science      4
      3          Art          3
                 Math         4
                 Science      4
      4          Art          3
                 Math         5
                 Science      5
B     1          Art          5
                 Math         5
                 Science      4
      2          Art          5
                 Math         5
                 Science      5
      3          Art          5
                 Math         5
                 Science      3
      4          Art          4
                 Math         5
                 Science      5

In [262]:
df.groupby(
    ['Class','Subject',])['Score'].mean()
#平均成绩

Class  Subject
A      Art        4.00
       Math       4.25
       Science    4.25
B      Art        4.75
       Math       5.00
       Science    4.25
Name: Score, dtype: float64

In [266]:
df.groupby(
    ['Class','Student ID'])['Score'].mean()

Class  Student ID
A      1             4.000000
       2             4.666667
       3             3.666667
       4             4.333333
B      1             4.666667
       2             5.000000
       3             4.333333
       4             4.666667
Name: Score, dtype: float64

In [268]:
df.groupby(
    ['Class','Student ID'])

In [272]:
df.groupby('Subject')['Score'].mean()

Subject
Art        4.375
Math       4.625
Science    4.250
Name: Score, dtype: float64

In [276]:
df.groupby(['Class','Student ID'])['Score'].sum().sort_values(ascending=False)

Class  Student ID
B      2             15
A      2             14
B      1             14
       4             14
A      4             13
B      3             13
A      1             12
       3             11
Name: Score, dtype: int64

In [280]:
import seaborn as sns
import pandas as pd

iris_df = sns.load_dataset("iris")
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [282]:
def map_fnc(sepal_length):
    if sepal_length<5:
        return 'D'
    elif 5<= sepal_length <6:
        return 'C'
    elif 6<= sepal_length <7:
        return 'B'
    else:
        'A'

In [284]:
iris_df['ctg'] = iris_df['sepal_length'].apply(map_fnc)
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species ctg
0             5.1          3.5           1.4          0.2     setosa   C
1             4.9          3.0           1.4          0.2     setosa   D
2             4.7          3.2           1.3          0.2     setosa   D
3             4.6          3.1           1.5          0.2     setosa   D
4             5.0          3.6           1.4          0.2     setosa   C
..            ...          ...           ...          ...        ...  ..
145           6.7          3.0           5.2          2.3  virginica   B
146           6.3          2.5           5.0          1.9  virginica   B
147           6.5          3.0           5.2          2.0  virginica   B
148           6.2          3.4           5.4          2.3  virginica   B
149           5.9          3.0           5.1          1.8  virginica   C

[150 rows x 6 columns]

In [286]:
import seaborn as sns
import pandas as pd

In [288]:
iris_df = sns.load_dataset("iris")
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [294]:
iris_df.groupby('species')['sepal_length'].apply( lambda x: x.min())

species
setosa        4.3
versicolor    4.9
virginica     4.9
Name: sepal_length, dtype: float64

In [296]:
import seaborn as sns
import pandas as pd

In [298]:
iris_df = sns.load_dataset("iris")
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [300]:
mean_X2_by_species = iris_df.groupby(
    'species')['petal_width'].mean()
mean_X2_by_species

species
setosa        0.246
versicolor    1.326
virginica     2.026
Name: petal_width, dtype: float64

In [302]:
def map_petal_width(petal_width,species):
    if petal_width > mean_X2_by_species[species]:
        return "YES"
    else:
        return "NO"

In [306]:
iris_df['greater_than_mean'] = iris_df.apply(lambda
        row: map_petal_width(row['petal_width'],
                             row['species']),axis=1)
iris_df

,sepal_length,sepal_width,petal_length,petal_width,species,greater_than_mean
0,5.1,3.5,1.4,0.2,setosa,NO
1,4.9,3.0,1.4,0.2,setosa,NO
2,4.7,3.2,1.3,0.2,setosa,NO
3,4.6,3.1,1.5,0.2,setosa,NO
4,5.0,3.6,1.4,0.2,setosa,NO
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,YES
146,6.3,2.5,5.0,1.9,virginica,NO
147,6.5,3.0,5.2,2.0,virginica,NO
148,6.2,3.4,5.4,2.3,virginica,YES
149,5.9,3.0,5.1,1.8,virginica,NO