In [33]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

In [35]:
iris = load_iris()
X = iris.data#提取4个特征 为Numpy数组

In [37]:
print(iris.feature_names) #提取特征名称

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [39]:
y = iris.target #提取鸢尾花数据集标签,Numpy数组 #?
print(np.unique(y)) #返回特殊标签0,1,2

[0 1 2]

In [41]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']

In [43]:
X_df = pd.DataFrame(X,columns = ['X1','X2','X3','X4'])
X_df.head()

    X1   X2   X3   X4
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [17]:
X_df.tail()

      X1   X2   X3   X4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [21]:
round(X_df.describe(),2)

           X1      X2      X3      X4
count  150.00  150.00  150.00  150.00
mean     5.84    3.06    3.76    1.20
std      0.83    0.44    1.77    0.76
min      4.30    2.00    1.00    0.10
25%      5.10    2.80    1.60    0.30
50%      5.80    3.00    4.35    1.30
75%      6.40    3.30    5.10    1.80
max      7.90    4.40    6.90    2.50

In [29]:
X,y = load_iris(as_frame = True,return_X_y = True) #X为Dataframe格式y为PandasSeries
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [31]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64